# Binds to AP interface, serves exactly 2 IPs (Pi + 1 client)
interface=wlan0
no-dhcp-interface=eth0
bind-interfaces
dhcp-range=192.168.4.2,192.168.4.2,12h
dhcp-option=3,192.168.4.1
dhcp-option=6,192.168.4.1
# Don't resolve dns, no upstream
no-resolv
no-poll
